spring:
  application:
    name: distributed-Rate-Limiter

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${DB_USER:rate_limiter}
    password: ${DB_PASSWORD:rate_limiter_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30s

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  consumer:
    group-id: rate-limiter-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
